name: torchok
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - omegaconf=2.1.2
  - pip=22.0.4
  - python=3.7
  - pytorch=1.9.0
  - torchvision=0.10.0
  - cudatoolkit=11.1
  - pytorch-lightning=1.6.2
  - pip:
      - opencv-python==4.5.3.56
      - albumentations>=1.0.3
