name: torchok
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - hydra-core=1.2.0
  - faiss=1.7.2
  - pandas=1.3.5
  - pillow=9.1.0
  - pip=22.0.4
  - python=3.7
  - pytorch=1.9.0
  - torchvision=0.10.0
  - cudatoolkit=11.1
  - pytorch-lightning=1.6.2
  - torchmetrics=0.8.2
  - pip:
      - opencv-python==4.5.3.56
      - albumentations>=1.0.3
      - ranx==0.1.12
