name: torchok
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.12
  - pip=21.3.1
  - pydantic=1.8.2
  - pyyaml=6.0
  - pytorch=1.10
  - torchvision=0.11.1
  - cudatoolkit=11.3
  - pytorch-lightning=1.5
  - pandas=1.3.4
  - scikit-learn=1.0.1
  - faiss-cpu=1.7.1
  - seaborn=0.11.2
  - jupyterlab=3.2.1
  - boto3=1.17.93
  - mlflow=1.14.1
  - pymysql=1.0.2
  - pip:
    - rank_eval==0.1
    - opencv-python==4.5.4.58
    - albumentations==1.1.0
    - sagemaker==2.68.0
    - parameterized==0.8.1
    - jedi==0.17.2
    - rich==10.12.0
