task:
  name: ClassificationTask
  params:
    backbone_name: efficientnet_lite0
    backbone_params:
      pretrained: true
      in_chans: 3
    pooling_name: PoolingLinear
    pooling_params:
      out_features: 256
    head_name: ClassificationHead
    head_params:
      num_classes: &num_classes 5749
    input_size: [3, &height 64, &width 64]

#restore_path: ''

loss:
  loss_list:
    - name: CrossEntropyLoss
      params:
        target_fields:
          target: target
          input: prediction

optimizers:
  name: SGD
  params:
    lr: &max_lr 0.1
    weight_decay: 0.00005
    momentum: 0.9
    nesterov: true

schedulers:
  name: OneCycleLR
  params:
    epochs: 10
    steps_per_epoch: 500
    max_lr: *max_lr
  aux_params:
    interval: step

data:
  common_params:
    data_folder: "${SM_CHANNEL_TRAINING}"


  train_params:
    name: ImageDataset
    dataloader_params: &dataloader_params
      batch_size: 20
      num_workers: 8
      shuffle: true
      drop_last: false
    params:
      path_to_datalist: "lfw_imgs.csv"
    transform:
      - &resize
          name: Resize
          params:
            height: *height
            width: *width
      - &normalize
        name: Normalize
        params:
          mean: [0.5, 0.5, 0.5]
          std: [0.5, 0.5, 0.5]
      - &totensor
        name: ToTensorV2

  valid_params:
    name: ImageDataset
    dataloader_params: *dataloader_params
    params:
      path_to_datalist: "lfw_imgs.csv"
    transform:
      - *resize
      - *normalize
      - *totensor

trainer:
  gpus: 1
  max_epochs: 70
  limit_train_batches: 500
  limit_val_batches: 16
  progress_bar_refresh_rate: 1
  check_val_every_n_epoch: 1
  precision: 32

log_dir: &logdir 'logs/face_recognition'
experiment_name:  &exp_name efficientnet_b0

logger:
  logger: tensorboard
  log_graph: false

checkpoint:
  monitor: valid/loss
  save_last: true
  mode: min

profiler:
  name: 'simple'
  save_profile: false

metrics:
  - name: AccuracyMeter
    params:
      name: accuracy
      target_fields:
        target: target
        prediction: prediction

