task:
  name: SegmentationTask
  params:
    segmenter_name: UPerNet
    segmenter_params:
      num_classes: 1
    backbone_name: swin_tiny_patch4_window7_224
    backbone_params:
      in_chans: &num_channels 3
      pretrained: true
#    input_size: [ *num_channels, &height 256, &width 256 ]
    input_size: [*num_channels, &height 448, &width 448]

loss:
  loss_list:
    - name: DiceLoss
      params:
        mode: binary
        target_fields:
          target: target
          input: logits
    - name: LovaszLoss
      params:
        mode: binary
        target_fields:
          target: target
          input: logits
    - name: BCEWithLogitsLoss
      params:
        target_fields:
          target: target
          input: logits

optimizers:
  name: AdamW
  params:
    lr: &initial_lr 0.0001
    weight_decay: 0.01

schedulers:
  name: CosineAnnealingWarmRestarts
  params:
    T_0: 5
    T_mult: 2

data:
  common_params:
    data_folder: '../../../datasets/leedsbutterfly'
    target_column: mask_path
    input_dtype: float16

  train_params:
    name: ImageSegmentationDataset
    dataloader_params: &dataloader_params
      batch_size: 16
      num_workers: 16
      shuffle: true
      drop_last: false
    params:
      path_to_datalist: "train.csv"
    transform:
      - &normalize
        name: Normalize
        params:
          mean: [ 0.485, 0.456, 0.406 ]
          std: [ 0.229, 0.224, 0.225 ]
      - &totensor
        name: ToTensorV2
    augment:
      - name: RandomResizedCrop
        params:
          height: *height
          width: *width
          scale: [ 0.6, 1.0 ]
          ratio: [ 0.75, 1.3 ]
      - name: ShiftScaleRotate
        params:
          p: 1.0
          scale_limit: 0.3
          rotate_limit: [-180, 180]
          shift_limit: 0.0625
          border_mode: 0
      - &resize
        name: LongestMaxSize
        params:
          max_size: *height
          interpolation: 2
          p: 1
      - name: OneOf
        params:
          transforms:
            - name: Blur
            - name: GaussianBlur
            - name: MedianBlur
            - name: MotionBlur
          p: 0.2
      - name: RandomFog
        params:
          p: 0.2
      - name: RandomShadow
        params:
          p: 0.2
      - name: RandomSunFlare
        params:
          p: 0.2
      - name: ChannelDropout
        params:
          p: 0.2
      - name: ChannelShuffle
        params:
          p: 0.2
      - name: ColorJitter
        params:
          p: 0.2
      - name: OneOf
        params:
          transforms:
            - name: ImageCompression
              params:
                quality_lower: 90
            - name: GaussNoise
      - name: OpticalDistortion
        params:
          p: 0.3
      - name: Equalize
        params:
          p: 0.3
      - name: ToGray
        params:
          p: 0.3
      - &pad
        name: PadIfNeeded
        params:
          min_height: *height
          min_width: *width
          border_mode: 0
          p: 1.0

  valid_params:
    name: ImageSegmentationDataset
    dataloader_params: *dataloader_params
    params:
      path_to_datalist: "valid.csv"
    transform:
      - *normalize
      - *totensor
    augment:
      - *resize
      - *pad

trainer:
  gpus: [0]
  max_epochs: 150
  progress_bar_refresh_rate: 1
  check_val_every_n_epoch: 1
  precision: 16
  amp_level: 'O2'
  amp_backend: 'apex'

log_dir: 'logs/butterflies'
experiment_name: swin_tiny

logger:
  logger: tensorboard
  log_graph: false

checkpoint:
  monitor: valid/IoU_meter
#  monitor: valid/loss
  save_last: true
  mode: max
  every_n_val_epochs: 1

profiler:
  name: simple
  save_profile: false

metrics:
  - name: IntersectionOverUnionMeter
    params:
      name: IoU_meter
      target_class: 1
      binary_mod: true
      target_fields:
        target: target
        prediction: logits
  - name: DiceMeter
    params:
      name: Dice_meter
      target_class: 1
      binary_mod: true
      target_fields:
        target: target
        prediction: logits
